apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: snoop
  labels:
    app: mailhog
    tier: dev
spec:
  type: NodePort
  selector:
    app: mailhog
  ports:
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025
    - name: http
      protocol: TCP
      port: 8025
      targetPort: 8025
      nodePort: 30300
